language: node_js
dist: trusty
node_js: 6
addons:
  #firefox: latest
  apt:
    sources:
      - google-chrome
      - ubuntu-toolchain-r-test
    packages:
      - google-chrome-stable
      - libstdc++-4.9-dev

env:
  - TASK="test"
  - TASK="docs"

before_script:
  - 'if [ "$TRAVIS_SECURE_ENV_VARS" == "false" ]; then
    echo "Secure environment variables disabled for unsecure build.  Unable to fully test.";
  elif [ "$TRAVIS_TAG" != "" ]; then
    echo "Tagged build, using account for tags.";
    SAUCE_USERNAME=$SAUCE_USERNAME_TAGS;
    SAUCE_ACCESS_KEY=$SAUCE_ACCESS_KEY_TAGS;
  elif [ "$TRAVIS_BRANCH" == "master" -a "$TRAVIS_PULL_REQUEST" == "false" ]; then
    echo "Master build, using account for master.";
    SAUCE_USERNAME=$SAUCE_USERNAME_MASTER;
    SAUCE_ACCESS_KEY=$SAUCE_ACCESS_KEY_MASTER;
  fi'

script:
  - 'if [ "$TASK" == "test" ]; then
    xvfb-run bin/build.coffee test -l &&
    test "$TRAVIS_SECURE_ENV_VARS" != "false" && bin/build.coffee test -s --fixed;
  fi'
  # if [ "$TRAVIS_BRANCH" == "master" -a "$TRAVIS_PULL_REQUEST" == "false" ]; then
  - 'if [ "$TASK" == "docs" ]; then
    if [ "1" == "1" ]; then
      openssl aes-256-cbc -K $encrypted_7f70595bf749_key -iv $encrypted_7f70595bf749_iv -in lib/deploy_key.enc -out lib/deploy_key -d &&
      chmod 600 lib/deploy_key &&
      npm install nodegit &&
      eval "$(ssh-agent -s)" &&
      ssh-add lib/deploy_key &&
      bin/build.coffee docs --publish --ssh-agent;
    else
      bin/build.coffee docs;
    fi
  fi'
