language: node_js
dist: trusty
node_js: 6
addons:
  #firefox: latest
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

before_script:
  - 'if [ "$TRAVIS_SECURE_ENV_VARS" == "false" ]; then
    echo "Secure environment variables disabled for unsecure build.  Unable to fully test.";
  elif [ "$TRAVIS_TAG" != "" ]; then
    SAUCE_USERNAME=$SAUCE_USERNAME_TAGS;
    SAUCE_ACCESS_KEY=$SAUCE_ACCESS_KEY_TAGS;
  elif [ "$TRAVIS_BRANCH" == "master" -a "$TRAVIS_PULL_REQUEST" == "false" ]; then
    SAUCE_USERNAME=$SAUCE_USERNAME_MASTER;
    SAUCE_ACCESS_KEY=$SAUCE_ACCESS_KEY_MASTER;
  fi'
  - npm install

script:
  - xvfb-run $(npm bin)/wct --skip-plugin sauce
  - test "$TRAVIS_SECURE_ENV_VARS" != "false" && $(npm bin)/wct --skip-plugin local
